// Generated by Wrangler by running `wrangler types`

interface Env {
	STORE: KVNamespace;
	SENTRY_DSN: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	OPENAI_API_KEY: string;
	OPENAI_GATEWAY: string;
	CF_VERSION_METADATA: { id: string; tag: string };
}
